import {describe,it,expect} from 'vitest';
import {dueDate,emptyStudio,transitionError,studioSchema,type Episode} from './model';
import {roboticsTemplate} from './template';
const episode=():Episode=>({id:crypto.randomUUID(),name:'Test',date:'2027-03-10T18:00:00.000Z',location:'London',description:'',stage:'proposed',studio:{...emptyStudio(),owner:'Alex',brief:'Robotics',plan:'Confirmed programme'}});
describe('episode workflow',()=>{
 it('checks every crossed approval gate and allows returning to earlier stages',()=>{const e=episode();expect(transitionError(e,'action_plan')).toBeNull();expect(transitionError(e,'in_progress')).toMatch(/owner/);expect(transitionError({...e,stage:'completed'},'planning')).toBeNull();expect(transitionError(e,'planning')).toBeNull();e.studio!.owner='';expect(transitionError(e,'planning')).toMatch(/owner/);e.archived=true;expect(transitionError(e,'planning')).toMatch(/Restore/);});
 it('requires dates for approved planning and assigned action tasks',()=>{const e=episode();e.stage='planning';e.date='';expect(transitionError(e,'action_plan')).toMatch(/date/);e.stage='action_plan';expect(transitionError(e,'in_progress')).toMatch(/owner/);});
 it('supports relative dates, fixed overrides and no invented date',()=>{const t=roboticsTemplate().tasks[0];expect(dueDate(t,'' )).toBeNull();expect(dueDate(t,'2027-03-10T18:00:00Z')?.toISOString()).toBe('2027-02-03T18:00:00.000Z');t.dueAt='2027-02-10T10:00:00Z';expect(dueDate(t,'')?.toISOString()).toBe('2027-02-10T10:00:00.000Z');});
 it('allows post-event work after completion but requires it to finish review',()=>{const e=episode();e.stage='in_progress';e.studio!.tasks=roboticsTemplate().tasks.map(t=>({...t,done:t.phase!=='retrospective'}));expect(transitionError(e,'completed')).toBeNull();e.stage='retrospective';expect(transitionError(e,'improved')).toMatch(/checklist/);e.studio={...e.studio!,tasks:e.studio!.tasks.map(t=>({...t,done:true})),recap:'Recap',lessons:'Learning',improvements:'Next step'};expect(transitionError(e,'improved')).toBeNull();});
 it('preserves action status alongside legacy completion',()=>{const s=roboticsTemplate();s.tasks[0].status='doing';const parsed=studioSchema.parse(s);expect(parsed.tasks[0].status).toBe('doing');expect(parsed.tasks[0].done).toBe(false);expect(parsed.tasks[1].status).toBeUndefined();});
 it('rejects duplicate tasks and unsafe cover URLs',()=>{const s=roboticsTemplate();expect(studioSchema.safeParse(s).success).toBe(true);s.tasks.push(s.tasks[0]);expect(studioSchema.safeParse(s).success).toBe(false);expect(studioSchema.safeParse({...emptyStudio(),cover:'javascript:alert(1)'}).success).toBe(false);});
});
