import type {Metadata} from 'next';
import Link from 'next/link';
import LegalPage from '@/components/LegalPage';
export const metadata:Metadata={title:'Privacy notice | Physical I/O',description:'How Physical I/O handles member information, Ohi conversations, voice, camera input and community communications.',alternates:{canonical:'/privacy'}};
export default function Page(){return <LegalPage title="Privacy notice">
<p>Yiguan Liu operates Physical I/O and is responsible for the personal information described in this notice. This notice explains how information is handled through this website. Contact <a href="mailto:soul@physical-io.com">soul@physical-io.com</a> about your data or privacy questions.</p>
<h2>Information you provide</h2><p>Community signup collects your first and last name, email, city, professional role, experience, work interests, an optional website link and a required LinkedIn profile link, community goals, preferred event formats and optional suggestions. We also record your signup time and consent preferences. This supports membership administration, relevant activities and communications you choose to receive.</p>
<h2>Ohi, voice and camera</h2><p>Messages sent to Ohi are processed by OpenAI to generate responses. Voice recordings used for transcription and live call audio are sent to OpenAI; Ohi’s spoken replies are AI-generated. During a video call, the service sends a camera snapshot approximately every two seconds to OpenAI. The separate camera-depth lighting mode processes camera frames on your device. It is not the same as a video call.</p><p>The current chat interface keeps its conversation in browser memory. This does not mean service providers keep no records: hosting and AI providers may process logs and retain information under their applicable service arrangements. Avoid sharing sensitive or confidential information.</p>
<h2>Why we use information</h2><p>We use information you submit to respond to your requests and administer your membership. The signup flow asks for consent to store membership answers and offers a separate, optional choice for event and news emails. You can withdraw that consent. We also process limited technical information for legitimate interests in operating the website, preventing misuse and protecting the community, and where required to meet legal obligations.</p>
<h2>Service providers and access</h2><p>Supabase stores member records. Vercel hosts the website and provides web analytics. Resend delivers emails, including new-member notifications to the community team at soul@physical-io.com and anthony@physical-io.com. OpenAI processes the AI interactions described above. The Luma calendar is an external embed and registrations on Luma are subject to its own privacy information. Links to social networks take you to their services.</p><p>Authorised community administrators can access membership information for community operations. Hosting, database, email and AI services may process data outside the UK. Applicable transfer protections and provider arrangements depend on the services used; contact us for details about your information.</p>
<h2>Retention</h2><p>Membership records are kept for as long as needed to administer the membership and related requests. Retention also depends on consent, unresolved enquiries, security needs and legal obligations. Unsubscribe and consent records may need to be retained to respect your communication preferences. Contact us to request deletion or ask about retention of a particular record.</p>
<h2>Your choices and rights</h2><p>You can request access, correction, deletion or restriction of your personal information, object to relevant processing, and ask about data portability where applicable. You can withdraw consent without affecting processing that took place before withdrawal. Some rights depend on the circumstances and applicable law. You may complain to the <a href="https://ico.org.uk/make-a-complaint/">Information Commissioner’s Office</a> if you are unhappy with how your data is handled.</p>
<h2>Website storage</h2><p>Read our <Link href="/cookies">cookies and storage information</Link> for browser preferences, authentication and third-party embeds. Giving camera or microphone permission is optional, and you can revoke it in your browser settings.</p>
</LegalPage>;}
