import type {Metadata} from 'next';
import Link from 'next/link';
import LegalPage from '@/components/LegalPage';
export const metadata:Metadata={title:'Terms & conditions | Physical I/O',description:'Terms for using the Physical I/O website, Ohi AI guide and community membership services.',alternates:{canonical:'/terms'}};
export default function Page(){return <LegalPage title="Terms & conditions">
<p>Physical I/O is operated by Yiguan Liu. These terms apply when you use the Physical I/O website, its community signup service and Ohi, our AI community guide. If you have questions, contact <a href="mailto:soul@physical-io.com">soul@physical-io.com</a>.</p>
<h2>Community membership</h2><p>Provide accurate information and use an email address you are entitled to use. Joining does not guarantee event places, introductions, funding, work opportunities or access to every activity. You can ask the team to update or remove your membership details.</p>
<h2>Respectful use</h2><p>Respect other people and their privacy. Do not use the service to harass, discriminate, impersonate others, send spam, distribute unlawful material, or access systems or data without permission. We may restrict access where reasonably necessary to protect people or the service.</p>
<h2>Ohi and AI responses</h2><p>Ohi is an AI system. Its responses and generated voice may be inaccurate or incomplete. Verify event details with the organiser and important information with an appropriate source. Ohi does not provide professional legal, financial or medical advice, and its responses do not create commitments on behalf of the community.</p><p>Do not submit confidential material or personal information about other people without authority. Microphone and camera use is optional. See the <Link href="/privacy">privacy notice</Link> for how voice calls, video snapshots and local depth processing differ.</p>
<h2>Events and external services</h2><p>Event listings, tickets and external platforms may have their own terms. Fees, refunds, accessibility arrangements and cancellations depend on the relevant event information. These website terms do not replace an organiser’s booking terms or your statutory rights.</p>
<h2>Content and intellectual property</h2><p>You retain ownership of work you share. You must have permission to share it. Submitting material through the service allows us to process it as needed to provide the requested service; it does not transfer ownership or grant permission to publish it publicly. Physical I/O branding and website material may not be used in a way that falsely implies endorsement.</p>
<h2>Availability and responsibility</h2><p>We aim to keep information useful and the service available, but cannot guarantee uninterrupted access or that all content is current. We are not responsible for third-party services we do not control. Nothing in these terms excludes liability that cannot lawfully be excluded, including fraud or death or personal injury caused by negligence, or removes applicable consumer rights.</p>
<h2>Updates and questions</h2><p>We may update these terms when the service changes. The date above identifies this version. Contact the community team if you have a concern about how these terms apply.</p>
</LegalPage>;}
