'use client';
import { useEffect,useRef,useState } from 'react';
import { Toast,Button,Field,Alert,Dialog,Badge } from '@/workspace-ui/src';
type Preview={configured:boolean;message:string;eligibleCount:number;skippedCount:number;confirmation:string;sample:{name:string;email:string}[];counts:{status:string;count:number}[];campaign:{status:string}};
export default function CampaignDelivery({id,onComplete,autoSend=false}:{id:string;onComplete:()=>void;autoSend?:boolean}){
 const [preview,setPreview]=useState<Preview|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[confirm,setConfirm]=useState(false),[message,setMessage]=useState('');const pending=useRef<{signature:string;requestId:string}|null>(null),lock=useRef(false);
 async function load(){const r=await fetch(`/api/admin/campaigns?id=${id}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setPreview(d);}
 useEffect(()=>{let live=true;const refresh=()=>load().catch(e=>{if(live)setError(e.message);});void refresh();const timer=setInterval(()=>{if(!document.hidden)void refresh();},5000);return()=>{live=false;clearInterval(timer);};},[id]);
 const started=useRef(false);
 useEffect(()=>{if(autoSend&&preview&&!started.current){started.current=true;void send('send');}},[autoSend,preview]);
 async function send(action:'test'|'send'){
  if(lock.current||!preview)return;lock.current=true;setBusy(true);setError('');setConfirm(false);
  try{const signature=JSON.stringify({id,action,email,confirmation:preview.confirmation});if(pending.current?.signature!==signature)pending.current={signature,requestId:crypto.randomUUID()};const r=await fetch('/api/admin/campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action,requestId:pending.current.requestId,...(action==='test'?{email}:{confirmation:preview.confirmation})})});const d=await r.json();if(!r.ok)throw new Error(d.error);pending.current=null;setMessage(action==='test'?'Test accepted by the email provider.':'Sending in the background. You can close this window.');if(action==='send')onComplete();await load();}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}
 }
 return <section className="admin-stack"><h3>Delivery</h3>{error&&<Alert title="Delivery unavailable" tone="danger">{error}</Alert>}<Toast message={message} onDismiss={()=>setMessage('')}/>{preview&&<>{!preview.configured&&<Alert title="Email provider not configured">{preview.message}</Alert>}<p>{preview.eligibleCount} eligible · {preview.skippedCount} skipped</p><p className="admin-muted">Includes addresses without recorded opt-in. Unsubscribed, bounced, complained and archived records remain excluded.</p>{preview.sample.length>0&&<details><summary>Audience sample</summary>{preview.sample.map(m=><p key={m.email}>{m.name} · {m.email}</p>)}</details>}<div className="admin-inline">{preview.counts.map(c=><Badge key={c.status}>{c.status}: {c.count}</Badge>)}</div><form className="admin-stack" onSubmit={e=>{e.preventDefault();void send('test');}}><Field label="Test recipient" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/><Button type="submit" disabled={!preview.configured} busy={busy}>Send test email</Button></form>{preview.campaign.status==='draft'&&<Button variant="primary" disabled={!preview.configured||(!preview.eligibleCount&&preview.campaign.status==='draft')} busy={busy} onClick={()=>setConfirm(true)}>Review and send</Button>}<p className="admin-muted">Sending continues in the background, even if you close this panel or browser. Progress is saved in Communications. “Accepted” means the provider accepted the email, not inbox delivery.</p></>}
 {confirm&&<Alert title="Send this campaign?"><p>{preview?.eligibleCount} eligible members. The full eligible audience will be processed.</p><div className="admin-actions"><Button onClick={()=>setConfirm(false)}>Cancel</Button><Button variant="primary" busy={busy} onClick={()=>void send('send')}>Send email</Button></div></Alert>}
 </section>;
}
