'use client';

import { useEffect,useRef,useState } from 'react';
import { Plus,ArrowLeft,ArrowUpRight,Image as ImageIcon,Columns3,List,CalendarDays,Download,Sparkles,SlidersHorizontal } from 'lucide-react';
import { Button,Popover,Card,PageHeader,Toolbar,SearchField,Select,Tabs,Badge,Dialog,Field,TextArea,Alert,EmptyState,Skeleton,DataTable } from '@/workspace-ui/src';
import { CONTENT_STAGES,STAGE_META,PLATFORMS,PLATFORM_META,type Platform } from '@/lib/marketing/config';
import MarketingVisual from './MarketingVisual';
import type { NewsCandidate } from '@/lib/marketing/ai';
import type { ContentItem,ContentDetail,Template,MarketingCommand,Variant } from '@/lib/marketing/contracts';
const choices=(values:readonly string[])=>values.map(value=>({value,label:value.replace(/^./,c=>c.toUpperCase())}));
const date=(value:string|null)=>value?new Date(value).toLocaleDateString('en-GB',{day:'numeric',month:'short'}):'Not scheduled';
const blank={title:'',summary:'',body:'',tags:'',sourceUrl:'',owner:''};
const safeUrl=(url:string)=>/^https?:\/\//i.test(url)?url:undefined;

export default function MarketingWorkspace(){
 const [items,setItems]=useState<ContentItem[]>([]),[templates,setTemplates]=useState<Template[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [view,setView]=useState('list'),[query,setQuery]=useState(''),[stage,setStage]=useState('all'),[section,setSection]=useState('content');
 const [detail,setDetail]=useState<ContentDetail|null>(null),[opening,setOpening]=useState(false),[editorTab,setEditorTab]=useState('draft'),[form,setForm]=useState(blank),[create,setCreate]=useState(false),[busy,setBusy]=useState(false),[newTemplate,setNewTemplate]=useState(false);
 const [platform,setPlatform]=useState<Platform>('instagram'),[variant,setVariant]=useState({body:'',caption:'',status:'draft',permalink:'',templateId:'none',assetId:'none'}),[note,setNote]=useState(''),[scheduled,setScheduled]=useState(''),[nextStage,setNextStage]=useState('idea');
 const [discard,setDiscard]=useState(false);
 const leaveAction=useRef<(()=>void)|null>(null);
 function leave(action:()=>void){const dirty=detail&&editorTab==='draft'&&(form.title!==detail.title||form.summary!==detail.summary||form.body!==detail.body_markdown||form.tags!==detail.category_tags.join(', ')||form.sourceUrl!==detail.source_url||form.owner!==detail.assigned_to_name);if(dirty){leaveAction.current=action;setDiscard(true);}else action();}
 const discardDialog=<Dialog open={discard} onOpenChange={setDiscard} title="Discard unsaved changes?" description="Your saved story will remain unchanged."><div className="admin-actions"><Button onClick={()=>setDiscard(false)}>Keep editing</Button><Button variant="primary" onClick={()=>{setDiscard(false);if(detail)setForm({title:detail.title,summary:detail.summary,body:detail.body_markdown,tags:detail.category_tags.join(', '),sourceUrl:detail.source_url,owner:detail.assigned_to_name});leaveAction.current?.();}}>Discard changes</Button></div></Dialog>;
 const [discover,setDiscover]=useState(false),[topic,setTopic]=useState(''),[suggestions,setSuggestions]=useState<NewsCandidate[]>([]),[aiBusy,setAiBusy]=useState(false),[aiMessage,setAiMessage]=useState('');
 async function assist(payload:object){setAiBusy(true);setError('');try{const r=await fetch('/api/admin/marketing/assist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error);setAiMessage(d.provider==='local'?'Starter suggestions only: live AI was unavailable. Verify every claim before use.':'Suggestion ready. Review sources and facts before saving.');return d;}catch(e){setError((e as Error).message);return null;}finally{setAiBusy(false);}}
 const lock=useRef(false),pending=useRef<{signature:string;id:string}|null>(null);
 async function read(){const r=await fetch('/api/admin/marketing',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.items);setTemplates(d.templates);if(d.truncated)setNotice('Showing the latest 1,000 stories.');}
 useEffect(()=>{let live=true;read().catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[]);
 async function open(id:string){setOpening(true);setError('');try{const r=await fetch(`/api/admin/marketing?id=${encodeURIComponent(id)}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setDetail(d);setForm({title:d.title,summary:d.summary,body:d.body_markdown,tags:d.category_tags.join(', '),sourceUrl:d.source_url,owner:d.assigned_to_name});setNextStage(d.status);setScheduled(d.scheduled_at?new Date(Date.parse(d.scheduled_at)-new Date(d.scheduled_at).getTimezoneOffset()*60000).toISOString().slice(0,16):'');return d as ContentDetail;}catch(e){setError((e as Error).message);return null;}finally{setOpening(false);}}
 function selectVariant(p:Platform,d=detail){setPlatform(p);const v=d?.variants.find(v=>v.platform===p);setVariant({body:v?.body??d?.body_markdown??'',caption:v?.caption??'',status:v?.status==='ready'?'ready':'draft',permalink:v?.external_permalink??'',templateId:v?.template_id??'none',assetId:v?.rendered_asset_id??'none'});}
 async function save(command:MarketingCommand){if(lock.current)return null;lock.current=true;setBusy(true);setError('');setNotice('');try{const signature=JSON.stringify(command);if(pending.current?.signature!==signature)pending.current={signature,id:crypto.randomUUID()};const r=await fetch('/api/admin/marketing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command,requestId:pending.current.id})});const d=await r.json();if(!r.ok)throw new Error(d.error);pending.current=null;setNotice('Saved to the content studio.');try{await read();}catch{setNotice('Saved successfully. Reload the content list to see the latest records.');}return d.id as string;}catch(e){setError((e as Error).message);return null;}finally{lock.current=false;setBusy(false);}}
 async function saveStory(){const id=await save({action:'save',...(detail?{id:detail.id,version:detail.updated_at}:{}),...form,tags:form.tags.split(',').map(t=>t.trim()).filter(Boolean)});if(id){setCreate(false);await open(id);}return id;}
 function download(){if(!detail)return;const text=[`# ${detail.title}`,detail.summary,detail.body_markdown,...detail.variants.map(v=>`## ${PLATFORM_META[v.platform].label}\n\n${v.body}\n\n${v.caption}\n\n${v.external_permalink}`)].join('\n\n');const url=URL.createObjectURL(new Blob([text],{type:'text/markdown'}));const a=document.createElement('a');a.href=url;a.download=`${detail.title.replace(/[^a-z0-9]/gi,'-').slice(0,80)}.md`;a.click();URL.revokeObjectURL(url);}
 const filtered=items.filter(i=>(stage==='all'||i.status===stage)&&(section!=='ready'||['approved','scheduled'].includes(i.status))&&`${i.title} ${i.summary} ${i.category_tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 const fields=<><Field label="Title" required maxLength={200} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><TextArea label="Hook / summary" rows={3} value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/><div className="marketing-field-grid"><Field label="Topics" hint="Separate topics with commas." value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/><Field label="Owner" value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})}/></div><Field label="Source URL" type="url" value={form.sourceUrl} onChange={e=>setForm({...form,sourceUrl:e.target.value})}/></>;
 const messages=<>{error&&<Alert title="Unable to complete request" tone="danger">{error}</Alert>}{notice&&<p role="status" className="admin-muted">{notice}</p>}</>;
 if(loading)return <Skeleton label="Loading marketing content"/>;
 if(detail)return <div className="marketing-workspace">{discardDialog}<Toolbar><Button variant="ghost" onClick={()=>leave(()=>{setDetail(null);setError('');setNotice('');})}><ArrowLeft size={16}/>All content</Button><Badge>{STAGE_META[detail.status]?.label??detail.status}</Badge><Button variant="ghost" onClick={download}><Download size={16}/>Export copy</Button></Toolbar><PageHeader title={detail.title} description="One story. Every channel."/>{messages}<Tabs label="Content editor" value={editorTab} onValueChange={tab=>leave(()=>{setEditorTab(tab);if(tab==='platforms')selectVariant(platform);})} items={[
 {value:'draft',label:'Master draft',content:<form className="marketing-editor admin-stack" onSubmit={async e=>{e.preventDefault();await saveStory();}}>{fields}<Button variant="ghost" busy={aiBusy} onClick={async()=>{const d=await assist({action:'draft',title:form.title,hook:form.summary,sourceUrl:form.sourceUrl});if(d)setForm({...form,body:d.body});}}><Sparkles size={16}/>Suggest draft</Button>{aiMessage&&<p role="status" className="admin-muted">{aiMessage}</p>}<TextArea label="Master draft" hint="Write the shared story in Markdown, then adapt it for each channel." rows={16} value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/><div className="admin-actions"><Button type="submit" variant="primary" busy={busy}>Save draft</Button></div></form>},
 {value:'platforms',label:'Platform copy',content:<div className="marketing-editor admin-stack"><Select label="Channel" value={platform} onValueChange={p=>selectVariant(p as Platform)} options={PLATFORMS.map(p=>({value:p,label:PLATFORM_META[p].label}))}/><form className="admin-stack" onSubmit={async e=>{e.preventDefault();const id=await save({action:'variant',id:detail.id,platform,...variant,status:variant.status as 'draft'|'ready',templateId:variant.templateId==='none'?null:variant.templateId,assetId:variant.assetId==='none'?null:variant.assetId});if(id)await open(id);}}><Button variant="ghost" busy={aiBusy} onClick={async()=>{const d=await assist({action:'adapt',title:detail.title,master:detail.body_markdown,platform,tone:templates.find(t=>t.id===variant.templateId)?.editorial.tone??''});if(d)setVariant({...variant,body:d.body,caption:d.caption,status:'draft'});}}><Sparkles size={16}/>Suggest platform copy</Button>{aiMessage&&<p role="status" className="admin-muted">{aiMessage}</p>}<TextArea label={`${PLATFORM_META[platform].label} copy`} rows={12} value={variant.body} onChange={e=>setVariant({...variant,body:e.target.value})}/><Field label="Caption" value={variant.caption} onChange={e=>setVariant({...variant,caption:e.target.value})}/><div className="marketing-field-grid"><Select label="Editorial template" value={variant.templateId} onValueChange={templateId=>setVariant({...variant,templateId})} options={[{value:'none',label:'No template'},...templates.map(t=>({value:t.id,label:t.name}))]}/><Select label="Review status" value={variant.status} onValueChange={status=>setVariant({...variant,status})} options={choices(['draft','ready'])}/></div>{variant.templateId!=='none'&&<p className="admin-muted">{templates.find(t=>t.id===variant.templateId)?.editorial.tone}</p>}<Select label="Visual asset" value={variant.assetId} onValueChange={assetId=>setVariant({...variant,assetId})} options={[{value:'none',label:'No asset'},...detail.assets.map(a=>({value:a.id,label:a.alt_text||a.kind}))]}/><Field label="Published link" type="url" hint="Add the live link after posting to this channel." value={variant.permalink} onChange={e=>setVariant({...variant,permalink:e.target.value})}/><Button type="submit" variant="primary" busy={busy}>Save channel</Button></form></div>},
 {value:'visuals',label:'Visuals',content:<div className="admin-stack"><MarketingVisual title={detail.title}/>{detail.assets.length?<div className="marketing-assets">{detail.assets.map(a=><Card key={a.id}>{safeUrl(a.public_url)?<a href={safeUrl(a.public_url)} target="_blank" rel="noreferrer"><img src={safeUrl(a.public_url)} alt={a.alt_text||'Content visual'}/></a>:<div className="admin-cover"><ImageIcon/><span>Asset preview unavailable</span></div>}<p>{a.alt_text||'Untitled visual'}</p><Badge>{a.kind}</Badge></Card>)}</div>:<EmptyState title="No visuals yet" description="Saved content visuals will appear here."/>}</div>},
 {value:'review',label:'Review & schedule',content:<div className="marketing-editor admin-stack"><Card><h2>Channel readiness</h2>{detail.variants.length?detail.variants.map(v=><div className="marketing-readiness" key={v.id}><span>{PLATFORM_META[v.platform].label}</span><Badge>{v.status}</Badge></div>):<p className="admin-muted">Save at least one platform variant to begin review.</p>}</Card><form className="admin-stack" onSubmit={async e=>{e.preventDefault();const id=await save({action:'stage',id:detail.id,stage:nextStage as ContentItem['status'],...(nextStage==='scheduled'&&scheduled?{scheduledAt:new Date(scheduled).toISOString()}:{})});if(id)await open(id);}}><Select label="Workflow stage" value={nextStage} onValueChange={setNextStage} options={CONTENT_STAGES.map(s=>({value:s,label:STAGE_META[s].label}))}/>{nextStage==='scheduled'&&<Field label="Planned publish time" type="datetime-local" required value={scheduled} onChange={e=>setScheduled(e.target.value)}/>}<p className="admin-muted">Scheduling records an editorial date. Publish through your channel, then add its live link. No automatic posting or email delivery is triggered here.</p><Button type="submit" variant="primary" busy={busy}>Update stage</Button></form></div>},
 {value:'activity',label:'Activity',content:<div className="marketing-editor admin-stack"><form className="admin-stack" onSubmit={async e=>{e.preventDefault();if(await save({action:'note',id:detail.id,detail:note})){setNote('');await open(detail.id);}}}><TextArea label="Editorial note" required rows={3} value={note} onChange={e=>setNote(e.target.value)}/><Button type="submit" busy={busy}>Add note</Button></form>{detail.events.map(e=><Card key={e.id}><p>{e.detail}</p><small className="admin-muted">{e.actor_name} · {date(e.created_at)}</small></Card>)}</div>}
 ]}/></div>;
 const table=<div className="admin-table-frame"><DataTable label="Content stories" rows={filtered} rowKey={i=>i.id} columns={[{key:'title',label:'Story',render:i=><Button variant="ghost" onClick={()=>void open(i.id)}>{i.title}</Button>},{key:'stage',label:'Stage',render:i=><Badge>{STAGE_META[i.status]?.label??i.status}</Badge>},{key:'owner',label:'Owner',render:i=>i.assigned_to_name||'Unassigned'},{key:'date',label:'Planned',render:i=>date(i.scheduled_at)},{key:'channels',label:'Channels',render:i=>i.variants.length?i.variants.map(v=>PLATFORM_META[v.platform]?.label).join(', '):'No variants'}]}/></div>;
 return <div className="marketing-workspace"><PageHeader title="Content" description="Turn ideas into stories worth sharing." action={<div className="admin-actions"><Button variant="ghost" onClick={()=>setDiscover(true)}><Sparkles size={16}/>Find ideas</Button><Button variant="primary" onClick={()=>{setForm(blank);setError('');setCreate(true);}}><Plus size={16}/>New story</Button></div>}/>{messages}{section!=='templates'&&(<Toolbar><SearchField label="Search content" placeholder="Search stories or topics…" value={query} onChange={e=>setQuery(e.target.value)}/><Popover title="Filter content" trigger={<Button variant="ghost"><SlidersHorizontal size={16}/>Filters{stage!=='all'&&<Badge>{STAGE_META[stage as ContentItem['status']].label}</Badge>}</Button>}><Select label="Stage" value={stage} onValueChange={setStage} options={[{value:'all',label:'All stages'},...CONTENT_STAGES.map(s=>({value:s,label:STAGE_META[s].label}))]}/><Button variant="ghost" onClick={()=>{setStage('all');setQuery('');}}>Clear filters</Button></Popover></Toolbar>)}<Tabs label="Content sections" value={section} onValueChange={setSection} items={[
 {value:'content',label:<>All content <Badge>{items.length}</Badge></>,content:null},{value:'ready',label:<>Ready to post <Badge>{items.filter(i=>['approved','scheduled'].includes(i.status)).length}</Badge></>,content:null},{value:'templates',label:'Templates',content:null}]}/>
 {section==='templates'?<div className="admin-stack"><Toolbar><p className="admin-muted">Shared editorial direction for every channel.</p><Button onClick={()=>setNewTemplate(true)}><Plus size={16}/>New template</Button></Toolbar><div className="marketing-assets">{templates.map(t=><Card key={t.id}><h2>{t.name}</h2><p>{t.description}</p><p className="admin-muted">{t.editorial.tone||'No editorial guidance yet.'}</p></Card>)}</div>{!templates.length&&<EmptyState title="No templates yet" description="Create reusable editorial guidance for your team."/>}</div>:<><Tabs label="Content views" value={view} onValueChange={setView} items={[{value:'board',label:<><Columns3 size={16}/>Board</>,content:null},{value:'list',label:<><List size={16}/>List</>,content:null},{value:'calendar',label:<><CalendarDays size={16}/>Schedule</>,content:null}]}/>{opening&&<p role="status">Opening story…</p>}{!filtered.length?<EmptyState title={query||stage!=='all'?'No matching stories':section==='ready'?'Nothing ready to post yet':'Your next story starts here'} description={query||stage!=='all'?'Try a different search or clear the filters.':section==='ready'?'Approve your platform copy to add it to this queue.':'Capture an idea, write a draft, and prepare it for each channel.'} action={query||stage!=='all'?<Button variant="ghost" onClick={()=>{setQuery('');setStage('all');}}>Clear filters</Button>:section==='content'?<Button onClick={()=>{setForm(blank);setCreate(true);}}>Create story</Button>:undefined}/>:view==='list'?table:view==='calendar'?<div className="admin-stack">{[...filtered].sort((a,b)=>(a.scheduled_at??'9999').localeCompare(b.scheduled_at??'9999')).map(i=><Card key={i.id} className="marketing-schedule"><span>{date(i.scheduled_at)}</span><Button variant="ghost" onClick={()=>void open(i.id)}>{i.title}</Button><Badge>{STAGE_META[i.status].label}</Badge></Card>)}</div>:<div className="marketing-board" role="region" aria-label="Editorial board" tabIndex={0}>{CONTENT_STAGES.filter(s=>s!=='archived'&& (stage==='all'||stage===s) || stage==='archived'&&s==='archived').map(s=><section className="marketing-column" key={s}><header><h2>{STAGE_META[s].label}</h2><Badge>{filtered.filter(i=>i.status===s).length}</Badge></header>{filtered.filter(i=>i.status===s).map(i=><Card key={i.id}><Button variant="ghost" className="marketing-story-title" onClick={()=>{setEditorTab('draft');void open(i.id);}}>{i.title}<ArrowUpRight size={15}/></Button>{i.summary&&<p className="marketing-hook">{i.summary}</p>}<div className="marketing-tags">{i.category_tags.slice(0,2).map(t=><Badge key={t}>{t}</Badge>)}</div><small className="admin-muted">{i.assigned_to_name||'Unassigned'}{i.scheduled_at&&` · ${date(i.scheduled_at)}`}</small></Card>)}</section>)}</div>}</>}
 <Dialog open={discover} onOpenChange={setDiscover} title="Discover content ideas" description="Find a starting point, then review its source before drafting." kind="drawer"><div className="admin-stack"><Field label="Topic or angle" value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Physical AI, robotics, wearables…"/><Button busy={aiBusy} onClick={async()=>{const d=await assist({action:'discover',topic});if(d)setSuggestions(d.candidates);}}><Sparkles size={16}/>Find ideas</Button>{aiMessage&&<p role="status" className="admin-muted">{aiMessage}</p>}{error&&<Alert title="Discovery unavailable" tone="danger">{error}</Alert>}{suggestions.map((s,i)=><Card key={i} className="admin-stack"><h2>{s.title}</h2><p>{s.hook}</p>{safeUrl(s.sourceUrl)&&<a href={safeUrl(s.sourceUrl)} target="_blank" rel="noreferrer">Read source <ArrowUpRight size={14}/></a>}<Button onClick={()=>{setForm({...blank,title:s.title,summary:s.hook,tags:s.suggestedTags.join(', '),sourceUrl:safeUrl(s.sourceUrl)??''});setDiscover(false);setCreate(true);}}>Use idea</Button></Card>)}</div></Dialog>
 <Dialog open={create} onOpenChange={setCreate} title="New story" description="Capture the idea. Refine the details as you go."><form className="admin-stack" onSubmit={async e=>{e.preventDefault();await saveStory();}}>{fields}{error&&<Alert tone="danger" title="Check story">{error}</Alert>}<div className="admin-actions"><Button variant="ghost" onClick={()=>setCreate(false)}>Cancel</Button><Button type="submit" variant="primary" busy={busy}>Create story</Button></div></form></Dialog>
 <Dialog open={newTemplate} onOpenChange={setNewTemplate} title="New editorial template" description="Reusable guidance for platform copy."><form className="admin-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await save({action:'template',name:String(f.get('name')),description:String(f.get('description')),tone:String(f.get('tone'))}))setNewTemplate(false);}}><Field label="Name" name="name" required/><Field label="Description" name="description"/><TextArea label="Tone and guidance" name="tone" rows={5}/>{error&&<Alert title="Check template" tone="danger">{error}</Alert>}<Button type="submit" variant="primary" busy={busy}>Save template</Button></form></Dialog>
 </div>;
}
