'use client';
import { useEffect,useRef,useState } from 'react';
import { Download } from 'lucide-react';
import { Button,Field,Select,Alert } from '@/workspace-ui/src';
import LogoMark from '@/workspace-ui/app/LogoMark';
import { PLATFORMS,PLATFORM_META,type Platform } from '@/lib/marketing/config';

export default function MarketingVisual({title}:{title:string}){
 const [headline,setHeadline]=useState(title),[platform,setPlatform]=useState<Platform>('instagram'),[layout,setLayout]=useState('cover'),[photo,setPhoto]=useState(''),[error,setError]=useState('');
 const canvas=useRef<HTMLCanvasElement>(null),logo=useRef<HTMLDivElement>(null);
 useEffect(()=>()=>{if(photo)URL.revokeObjectURL(photo);},[photo]);
 useEffect(()=>{let cancelled=false;async function draw(){const c=canvas.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;await document.fonts.ready;const {width:w,height:h}=PLATFORM_META[platform].canvas;c.width=w;c.height=h;ctx.fillStyle='#000000';ctx.fillRect(0,0,w,h);
 if(photo){const img=new Image();img.src=photo;await img.decode().catch(()=>{});if(cancelled)return;if(img.naturalWidth){const targetH=layout==='split'?h*.6:h;const scale=Math.max(w/img.width,targetH/img.height);ctx.drawImage(img,(w-img.width*scale)/2,(targetH-img.height*scale)/2,img.width*scale,img.height*scale);}}
 const fade=ctx.createLinearGradient(0,h*.2,0,h);fade.addColorStop(0,'rgba(0,0,0,0)');fade.addColorStop(1,'rgba(0,0,0,.92)');ctx.fillStyle=fade;ctx.fillRect(0,0,w,h);const pad=w*.065;ctx.fillStyle='#ffffff';ctx.font=`600 ${w*.025}px Manrope, sans-serif`;ctx.fillText('Physical I/O',pad+w*.06,pad+w*.025);
 const svg=logo.current?.querySelector('svg');if(svg){const data=new XMLSerializer().serializeToString(svg).replace(/currentColor/g,'#ffffff');const img=new Image();img.src=`data:image/svg+xml;charset=utf-8,${encodeURIComponent(data)}`;await img.decode().catch(()=>{});if(cancelled)return;ctx.drawImage(img,pad,pad-w*.005,w*.044,w*.044);}
 ctx.font=`700 ${w*.063}px Manrope, sans-serif`;const words=headline.split(/\s+/);const lines:string[]=[];let line='';for(const word of words){if(ctx.measureText(`${line} ${word}`).width>w-pad*2&&line){lines.push(line);line=word;}else line=line?`${line} ${word}`:word;}if(line)lines.push(line);const visible=lines.slice(0,5);visible.forEach((l,i)=>ctx.fillText(l,pad,h-pad-(visible.length-1-i)*w*.077,w-pad*2));}void draw();return()=>{cancelled=true;};},[headline,platform,photo,layout]);
 return <div className="marketing-visual"><div className="admin-stack"><Field label="Visual headline" maxLength={180} value={headline} onChange={e=>setHeadline(e.target.value)}/><Select label="Format" value={platform} onValueChange={p=>setPlatform(p as Platform)} options={PLATFORMS.map(p=>({value:p,label:`${PLATFORM_META[p].label} · ${PLATFORM_META[p].canvas.width} × ${PLATFORM_META[p].canvas.height}`}))}/><Select label="Layout" value={layout} onValueChange={setLayout} options={[{value:'cover',label:'Full cover'},{value:'split',label:'Image + headline'}]}/><Field label="Cover image" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>10*1024*1024){setError('Choose an image smaller than 10 MB.');return;}setError('');setPhoto(URL.createObjectURL(f));}}/><p className="admin-muted">Crop is centered automatically. Export a PNG for manual posting; this preview stays on your device.</p>{error&&<Alert title="Check image" tone="danger">{error}</Alert>}<Button onClick={()=>canvas.current?.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`physical-io-${platform}.png`;a.click();URL.revokeObjectURL(url);})}><Download size={16}/>Export PNG</Button></div><canvas ref={canvas} aria-label="Marketing visual preview"/><div ref={logo} hidden><LogoMark/></div></div>;
}
