'use client';
import {useState} from 'react';
import {Avatar,PageHeader,Card,Field,Button,Badge,Alert,Toast} from '@/workspace-ui/src';
import {saveUserDetails,saveHeadshot} from '@/app/admin/profile/actions';

export default function UserDetails({name:initialName,email,avatarUrl}:{name:string;email:string;avatarUrl?:string}){
 const [photo,setPhoto]=useState(avatarUrl);
 async function updatePhoto(form:FormData){setBusy(true);setError('');try{const result=await saveHeadshot(form);if(result.error)setError(result.error);else{setPhoto(result.avatarUrl??undefined);setMessage('Headshot updated.');window.dispatchEvent(new Event('profile-updated'));}}catch{setError('Your headshot could not be saved. Please try again.');}finally{setBusy(false);}}
 const [name,setName]=useState(initialName),[savedName,setSavedName]=useState(initialName),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 return <div className="user-details-page"><PageHeader title="User details" description="Your profile in the admin workspace."/><Card className="admin-stack"><div className="admin-row"><div className="admin-inline"><Avatar name={savedName} src={photo}/><strong>{savedName}</strong></div><Badge>Administrator</Badge></div><div className="admin-stack"><Field label="Headshot" type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} hint="PNG, JPEG or WebP, up to 750 KB. No photo uses your initials." onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file){if(file.size>750*1024){setError('Choose an image smaller than 750 KB.');return;}const form=new FormData();form.set('headshot',file);void updatePhoto(form);}}}/>{photo&&<Button disabled={busy} onClick={()=>{const form=new FormData();form.set('remove','true');void updatePhoto(form);}}>Use name placeholder</Button>}</div><form className="admin-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const result=await saveUserDetails(name);if(result.error)setError(result.error);else if(result.name){setName(result.name);setSavedName(result.name);setMessage('User details saved.');window.dispatchEvent(new Event('profile-updated'));}}catch{setError('Your details could not be saved. Please try again.');}finally{setBusy(false);}}}><Field label="Name" required maxLength={100} autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/><Field label="Email" type="email" value={email} readOnly hint="The email address used to sign in."/>{error&&<Alert title="Unable to save details" tone="danger">{error}</Alert>}<div className="admin-actions"><Button type="submit" variant="primary" busy={busy} disabled={name.trim()===savedName}>Save details</Button></div></form></Card><Toast message={message} onDismiss={()=>setMessage('')}/></div>;
}
