import 'dotenv/config';
import {config} from 'dotenv';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {database} from '../../lib/admin/database';
import {mutateMarketing} from '../../lib/marketing/database';
import {initialVisual} from '../../lib/marketing/visual-model';
config({path:'.env.local',override:true,quiet:true});
async function main(){const pool=database();const db=await pool.connect();try{await db.query('BEGIN');await db.query(readFileSync('supabase/migrations/20260908204812_content_editor.sql','utf8'));const actor=()=>({id:crypto.randomUUID(),name:'Rollback verification',requestId:crypto.randomUUID()});const c=await mutateMarketing(db,{action:'category',name:'Rollback category'},actor());const item=await mutateMarketing(db,{action:'save',title:'Rollback story',summary:'',body:'Draft',tags:[],sourceUrl:'',owner:'',categoryId:c.id},actor());const id=item.id;await mutateMarketing(db,{action:'metadata',id,featured:true},actor());let row=(await db.query('select * from public.content_items where id=$1',[id])).rows[0];assert.equal(row.category_id,c.id);assert.equal(row.featured,true);await mutateMarketing(db,{action:'schedule',id,scheduledAt:'2027-01-04T09:00:00.000Z'},actor());row=(await db.query('select * from public.content_items where id=$1',[id])).rows[0];assert.equal(new Date(row.scheduled_at).toISOString(),'2027-01-04T09:00:00.000Z');const doc=initialVisual('Saved canvas');await mutateMarketing(db,{action:'visual',id,version:new Date(row.updated_at).toISOString(),document:doc},actor());row=(await db.query('select * from public.content_items where id=$1',[id])).rows[0];assert.equal(row.visual_document.layers[2].text,'Saved canvas');await mutateMarketing(db,{action:'preset',name:'Rollback preset',document:doc},actor());await mutateMarketing(db,{action:'stage',id,stage:'archived'},actor());await mutateMarketing(db,{action:'delete',id,version:new Date(row.updated_at).toISOString()},actor());assert.equal((await db.query('select id from public.content_items where id=$1',[id])).rowCount,0);assert.equal((await db.query('select * from public.content_categories where color in (select color from public.content_categories group by color having count(*)>1)')).rowCount,0);console.log('PASS: category, metadata, schedule, visual save, preset, archive and delete; all changes rolled back.');}finally{await db.query('ROLLBACK');db.release();await pool.end();}}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
