import {config} from 'dotenv';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {database,mutate,RecordConflict} from '../../lib/admin/database';
import {emptyStudio,type EventStudio} from '../../lib/events/model';
config({path:'.env.local',override:true,quiet:true});
async function main(){const pool=database(),db=await pool.connect();try{await db.query('BEGIN');if(!(await db.query("select to_regclass('public.event_initiatives') t")).rows[0].t)await db.query(readFileSync('supabase/migrations/20260908211557_event_initiatives.sql','utf8'));const actor={id:crypto.randomUUID(),name:'Event rollback verification'};let studio:EventStudio={...emptyStudio(),owner:'Alex',brief:'Test proposal',plan:'Confirmed test plan'};
 const event=await mutate(db,{action:'event.initiative.save',version:0,name:'Rollback episode',date:null,location:'',description:'',studio},actor);const id=event.id!;
 const state=async()=> (await db.query('select * from public.event_initiatives where event_id=$1',[id])).rows[0];
 assert.equal((await state()).version,1);
 await assert.rejects(()=>mutate(db,{action:'event.advance',id,version:0,stage:'planning'},actor),RecordConflict);
 await mutate(db,{action:'event.advance',id,version:1,stage:'planning'},actor);
 assert.equal((await state()).history[0].actor,actor.name);
 await assert.rejects(()=>mutate(db,{action:'event.advance',id,version:2,stage:'action_plan'},actor),/Confirm the plan/);
 await mutate(db,{action:'event.initiative.save',id,version:2,name:'Rollback episode',date:'2027-03-10T18:00:00Z',location:'London',description:'',studio},actor);
 await mutate(db,{action:'event.advance',id,version:3,stage:'action_plan'},actor);
 for(const kind of ['content','campaign','lead'] as const)await mutate(db,{action:'event.work.create',id,version:(await state()).version,kind,name:`Rollback ${kind}`,body:'Draft only'},actor);
 await mutate(db,{action:'event.feature',id,version:(await state()).version,featured:true},actor);
 assert.equal((await state()).studio.featured,true);
 await mutate(db,{action:'event.feature',id,version:(await state()).version,featured:false},actor);
 assert.equal((await state()).studio.featured,false);
 const links=(await state()).studio.links;assert.equal(links.length,3);
 assert.equal((await db.query('select status from public.campaigns where id=$1',[links[1].id])).rows[0].status,'draft');
 studio={...(await state()).studio,plan:'Changed plan'};
 await mutate(db,{action:'event.initiative.save',id,version:(await state()).version,name:'Rollback episode',date:'2027-03-10T18:00:00.000Z',location:'London',description:'',studio},actor);
 assert.equal((await state()).stage,'planning');
 await mutate(db,{action:'event.archive',id,version:(await state()).version,archived:true},actor);
 await assert.rejects(()=>mutate(db,{action:'event.advance',id,version:9,stage:'action_plan'},actor),RecordConflict);
 await mutate(db,{action:'event.delete',id,version:(await state()).version},actor);
 assert.equal((await db.query('select * from public.event_initiatives where event_id=$1',[id])).rowCount,0);
 assert.equal((await db.query('select * from public.content_items where id=$1',[links[0].id])).rowCount,1);
 const security=(await db.query("select relrowsecurity,has_table_privilege('anon','public.event_initiatives','SELECT') anon,has_table_privilege('authenticated','public.event_initiatives','SELECT') authenticated from pg_class where oid='public.event_initiatives'::regclass")).rows[0];assert.equal(security.relrowsecurity,true);assert.equal(security.anon,false);assert.equal(security.authenticated,false);
 console.log('PASS: event CRUD, nullable dates, approval gates, version conflicts, linked draft creation, reapproval, cascade safety and RLS. All test data rolled back.');
 }finally{await db.query('ROLLBACK');db.release();await pool.end();}}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
